[package]
name = "rust_microservices"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "auth"
path = "src/auth-service/main.rs"

[[bin]]
name = "health-check"
path = "src/health-check-service/main.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"

[dependencies]
